# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Frédéric <frosmont@free.fr>, 2014
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-01-27 06:15+0000\n"
"PO-Revision-Date: 2015-01-24 22:09+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/nova/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: nova/filters.py:79
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr "Filtre %s retourne 0 machines"

#: nova/wsgi.py:148
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr "%(name)s en écoute sur %(host)s : %(port)s"

#: nova/wsgi.py:253
msgid "Stopping WSGI server."
msgstr "Arrêt du serveur WSGI."

#: nova/wsgi.py:273
msgid "WSGI server has stopped."
msgstr "Le serveur WSGI a été arrêté."

#: nova/api/openstack/__init__.py:102
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr "%(url)s retourné avec HTTP %(status)d"

#: nova/api/openstack/__init__.py:291
msgid "V3 API has been disabled by configuration"
msgstr "L'API V3 a été désactivée par configuration "

#: nova/api/openstack/__init__.py:336
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:520
#, python-format
msgid "Fault thrown: %s"
msgstr "Erreur générée : %s"

#: nova/api/openstack/wsgi.py:523
#, python-format
msgid "HTTP exception thrown: %s"
msgstr "Exception HTTP générée : %s"

#: nova/cells/messaging.py:1136
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, updated_since="
"%(since_str)s"
msgstr ""
"Synchronisation forcée des instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"

#: nova/cells/scheduler.py:241
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s second(s)"
msgstr ""
"Aucune cellule disponible lors de la planification. Une nouvelle tentative "
"aura lieu dans %(sleep_time)s seconde(s)"

#: nova/cells/filters/target_cell.py:58
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler hint"
msgstr ""

#: nova/compute/api.py:1530
msgid "instance termination disabled"
msgstr "Arrêt de l'instance désactivé"

#: nova/compute/api.py:1543
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1615
msgid "Instance is already in deleting state, ignoring this request"
msgstr "L'instance est déjà dans un état de suppression, ignoré cette requête"

#: nova/compute/api.py:1660
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: %(status)s"
msgstr ""

#: nova/compute/api.py:1670
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1687
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1744
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/manager.py:287
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:747
#, python-format
msgid ""
"Deleting instance as its host (%(instance_host)s) is not equal to our host "
"(%(our_host)s)."
msgstr ""
"Suppression de l'instance car son hôte (%(instance_host)s) ne correspond pas "
"notre hôte (%(our_host)s)."

#: nova/compute/manager.py:762
msgid ""
"Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""
"L'instance a déjà été marquée comme supprimée, déréférencement de "
"l'hyperviseur."

#: nova/compute/manager.py:906
msgid ""
"Service started deleting the instance during the previous run, but did not "
"finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1031
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""
"Instance trouvée à l'état en cours de migration lors du démarrage. "
"Redéfinition de task_state"

#: nova/compute/manager.py:1053
msgid "Rebooting instance after nova-compute restart."
msgstr "Redémarrage de l'instance après redémarrage de nova-compute."

#: nova/compute/manager.py:1103
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:2571
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2615
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""
"L'instance est déjà éteinte dans l'hyperviseur quand l'arrêt est appelé."

#: nova/compute/manager.py:2799
msgid "disk on shared storage, recreating using existing disk"
msgstr ""
"Disque sur la mémoire partagée ; recréation à l'aide du disque existant"

#: nova/compute/manager.py:2803
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:2891
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr "Restauration de l'état original de la machine virtuelle : '%s'"

#: nova/compute/manager.py:2922
#, python-format
msgid "Detaching from volume api: %s"
msgstr "Déconnexion de l'API volume : %s"

#: nova/compute/manager.py:3442
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3463
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3651
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:5113
msgid "_post_live_migration() is started.."
msgstr "_post_live_migration() est démarré.."

#: nova/compute/manager.py:5193
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5195
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""
"Vous pouvez voir l'erreur \"libvirt : erreur QEMU : Domaine non trouvé : "
"aucun domaine avec un nom correspondant.\" Cette erreur peut être ignorée."

#: nova/compute/manager.py:5220
msgid "Post operation of migration started"
msgstr "Opération postérieure à la migration démarrée"

#: nova/compute/manager.py:5483
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""
"Détection de %(migration_count)d migrations non confirmées antérieures à "
"%(confirm_window)d secondes"

#: nova/compute/manager.py:5498
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""
"Confirmation automatique de la migration %(migration_id)s pour l'instance "
"%(instance_uuid)s"

#: nova/compute/manager.py:5552
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5600
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""
"Exécution de l'audit d'utilisation de l'instance pour l'hôte %(host)s de "
"%(begin_time)s à %(end_time)s. %(number_instances)s instances."

#: nova/compute/manager.py:5648
msgid "Updating bandwidth usage cache"
msgstr "Mise à jour du cache d'utilisation de la bande passante"

#: nova/compute/manager.py:5829 nova/compute/manager.py:5886
#, python-format
msgid ""
"During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""
"Durant sync_power_state l'instance à une tâche en attente (%(task)s). Passer."

#: nova/compute/manager.py:5873
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to "
"host %(dst)s"
msgstr ""
"Lors du processus sync_power, l'instance a été déplacée depuis l'hôte "
"%(src)s vers l'hôte %(dst)s"

#: nova/compute/manager.py:6032
msgid "Reclaiming deleted instance"
msgstr "Récupération de l'instance supprimée"

#: nova/compute/manager.py:6114
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6132
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6180
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6190
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr "Rétablissement de l'instance en statut ACTIVE après: %s"

#: nova/compute/resource_tracker.py:419
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr "Enregistrement Compute_service créé pour %(host)s:%(node)s"

#: nova/compute/resource_tracker.py:436
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr "Enregistrement Compute_service mis à jour pour %(host)s:%(node)s"

#: nova/conductor/api.py:317
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/db/sqlalchemy/api.py:3321
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""
"quota_usages de la synchronisation, la mise à jour. project_id : "
"%(project_id)s, user_id : %(user_id)s, ressource : %(res)s, suivi "
"d'utilisation : %(tracked_use)s, utilisation effective : %(in_use)s"

#: nova/db/sqlalchemy/api.py:5125
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must have "
"been rebooted or crashed. Updating totals."
msgstr ""
"Les statistiques du volume(%s) sont inférieures à celles de la base de "
"données. L'instance a dûe être redémarrée (volontairement ou plantage). "
"Synchronisation des données."

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent index "
"already exists."
msgstr ""
"Passé l'ajout de reservations_deleted_expire_idx car un index équivalent "
"existe déjà."

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:58
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:58
msgid ""
"Skipped removing reservations_deleted_expire_idx because index does not "
"exist."
msgstr ""
"Passé le retrait de reservations_deleted_expire_idx car l'index n'existe pas."

#: nova/image/s3.py:386
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:164
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:220 nova/network/neutronv2/api.py:1024
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""
"ré-affectation de l'adresse IP flottante %(address)s depuis l'instance "
"%(instance_id)s"

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr "Chargement du pilote de réseau '%s'"

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr "Démarrage de la migration réseau pour instance %s"

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:334
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:507
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:566
#, python-format
msgid "Network deallocated for instance (fixed ips: '%s')"
msgstr ""

#: nova/network/minidns.py:201
#, python-format
msgid "deleted %s"
msgstr "suppression de %s"

#: nova/network/neutronv2/api.py:623
#, python-format
msgid "Unable to reset device ID for port %s"
msgstr ""

#: nova/network/security_group/neutron_driver.py:446
#: nova/network/security_group/neutron_driver.py:501
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr "Ajout du groupe de sécurité %(security_group_id)s au port %(port_id)s"

#: nova/openstack/common/eventlet_backdoor.py:146
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr "Eventlet backdoor en écoute sur le port %(port)s for process %(pid)d"

#: nova/openstack/common/periodic_task.py:132
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "Tâche périodique %(task)s ignorée car son intervalle est négatif"

#: nova/openstack/common/periodic_task.py:137
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "Tâche périodique %(task)s car elle est désactivée"

#: nova/openstack/common/policy.py:275
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: nova/openstack/common/service.py:174
#, python-format
msgid "Caught %s, exiting"
msgstr "%s interceptée, sortie"

#: nova/openstack/common/service.py:232
msgid "Parent process has died unexpectedly, exiting"
msgstr "Processus parent arrêté de manière inattendue, sortie"

#: nova/openstack/common/service.py:263
#, python-format
msgid "Child caught %s, exiting"
msgstr "L'enfant a reçu %s, sortie"

#: nova/openstack/common/service.py:302
msgid "Forking too fast, sleeping"
msgstr "Bifurcation trop rapide, pause"

#: nova/openstack/common/service.py:321
#, python-format
msgid "Started child %d"
msgstr "Enfant démarré %d"

#: nova/openstack/common/service.py:331
#, python-format
msgid "Starting %d workers"
msgstr "Démarrage des travailleurs %d"

#: nova/openstack/common/service.py:348
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "Enfant %(pid)d arrêté par le signal %(sig)d"

#: nova/openstack/common/service.py:352
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "Processus fils %(pid)s terminé avec le status %(code)d"

#: nova/openstack/common/service.py:391
#, python-format
msgid "Caught %s, stopping children"
msgstr "%s interceptée, arrêt de l'enfant"

#: nova/openstack/common/service.py:400
msgid "Wait called after thread killed. Cleaning up."
msgstr ""

#: nova/openstack/common/service.py:416
#, python-format
msgid "Waiting on %d children to exit"
msgstr "En attente %d enfants pour sortie"

#: nova/scheduler/host_manager.py:428
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""
"Suppression du noeud de traitement mort %(host)s:%(node)s du planificateur"

#: nova/scheduler/client/report.py:52
#, python-format
msgid "Compute_service record updated for %s"
msgstr "Enregistrement de Compute_service mis à jour pour %s"

#: nova/scheduler/filters/utils.py:65
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""
"%(num_values)d valeurs trouvées, et c'est la valeur minimale qui sera "
"utilisée."

#: nova/virt/block_device.py:222
#, python-format
msgid "preserve multipath_id %s"
msgstr "conserver multipath_id %s"

#: nova/virt/driver.py:1387
#, python-format
msgid "Loading compute driver '%s'"
msgstr "Chargement du pilote de calcul '%s'"

#: nova/virt/firewall.py:173 nova/virt/libvirt/firewall.py:344
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""
"Vous avez essayé d'annuler le filtre d'une instance qui n'est pas filtrée"

#: nova/virt/firewall.py:443
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr "chaîne d'instance %s disparaît durant le rafraîchissement, à passer"

#: nova/virt/disk/mount/api.py:121
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""
"L'allocation d'unité a échoué. Une nouvelle tentative aura lieu dans 2 "
"secondes."

#: nova/virt/disk/mount/loop.py:33
#, python-format
msgid "Loop mount error: %s"
msgstr "Erreur d'installation en boucle : %s"

#: nova/virt/disk/mount/nbd.py:91 nova/virt/disk/mount/nbd.py:104
#, python-format
msgid "NBD mount error: %s"
msgstr "Erreur d'installation NBD : %s"

#: nova/virt/disk/vfs/api.py:67
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/basevolumeutils.py:74
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""
"Le nom d'initiateur ISCSI est introuvable. Le nom par défaut est sélectionné."

#: nova/virt/hyperv/vmops.py:260
msgid "Spawning new instance"
msgstr "Génération d'une nouvelle instance"

#: nova/virt/hyperv/vmops.py:375 nova/virt/vmwareapi/vmops.py:617
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:388 nova/virt/libvirt/driver.py:2783
#, python-format
msgid "Creating config drive at %(path)s"
msgstr "Création de l'unité de config à %(path)s"

#: nova/virt/hyperv/vmops.py:438
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:490
msgid "Soft shutdown succeeded."
msgstr "Arrêt logiciel réussi."

#: nova/virt/libvirt/driver.py:512
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:663
msgid "Instance destroyed successfully."
msgstr "Instance détruite avec succès."

#: nova/virt/libvirt/driver.py:673
msgid "Instance may be started again."
msgstr "L'instance peut être redémarrée."

#: nova/virt/libvirt/driver.py:683
msgid "Going to destroy instance again."
msgstr "Tentative de redestruction de l'instance."

#: nova/virt/libvirt/driver.py:1324
msgid "Beginning live snapshot process"
msgstr "Démarrage du processus d'instantané en temps réel"

#: nova/virt/libvirt/driver.py:1327
msgid "Beginning cold snapshot process"
msgstr "Démarrage du processus d'instantané à froid"

#: nova/virt/libvirt/driver.py:1357
msgid "Snapshot extracted, beginning image upload"
msgstr "Instantané extrait, démarrage du téléchargement d'image"

#: nova/virt/libvirt/driver.py:1369
msgid "Snapshot image upload complete"
msgstr "Téléchargement d'image instantanée terminé"

#: nova/virt/libvirt/driver.py:1941
msgid "Instance soft rebooted successfully."
msgstr "Instance redémarrée par logiciel avec succès."

#: nova/virt/libvirt/driver.py:1984
msgid "Instance shutdown successfully."
msgstr "L'instance s'est arrêtée avec succès."

#: nova/virt/libvirt/driver.py:1992
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr "L'instance a sans doute été redémarrée par logiciel ; retour en cours."

#: nova/virt/libvirt/driver.py:2070
msgid "Instance rebooted successfully."
msgstr "L'instance a redémarré avec succès."

#: nova/virt/libvirt/driver.py:2113
msgid "Instance already shutdown."
msgstr "Instance déjà arrêtée."

#: nova/virt/libvirt/driver.py:2129
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr "Arrêt de l'instance réussie après %d secondes."

#: nova/virt/libvirt/driver.py:2158
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr "Échec de l'arrêt de l'instance dans %d seconds. "

#: nova/virt/libvirt/driver.py:2326
msgid "Instance spawned successfully."
msgstr "Instance générée avec succès."

#: nova/virt/libvirt/driver.py:2342
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr "data: %(data)r, fpath: %(fpath)r"

#: nova/virt/libvirt/driver.py:2377
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2388 nova/virt/libvirt/driver.py:2415
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr "Journal de console tronqué retourné, %d octets ignorés"

#: nova/virt/libvirt/driver.py:2646
msgid "Creating image"
msgstr "Création de l'image"

#: nova/virt/libvirt/driver.py:2774
msgid "Using config drive"
msgstr "Utilisation de l'unité de config"

#: nova/virt/libvirt/driver.py:3545
msgid "Configuring timezone for windows instance to localtime"
msgstr "Configurer le fuseau horaire pour l'instance windows en heure locale"

#: nova/virt/libvirt/driver.py:4667
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. Instance="
"%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""
"Echec lors de la récupération des statistiques, le périphérique est peut-"
"être détaché. Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s "
"Erreur=%(e)s"

#: nova/virt/libvirt/driver.py:4673
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats for "
"device"
msgstr ""
"Domaine introuvable dans libvirt pour l'instance %s. Impossible d'obtenir "
"les stats de bloc pour l'unité"

#: nova/virt/libvirt/driver.py:4978
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr "L'instance lancée a l'info CPU : %s"

#: nova/virt/libvirt/driver.py:5772
msgid "Instance running successfully."
msgstr "L'instance s'exécute avec succès."

#: nova/virt/libvirt/driver.py:6137
#, python-format
msgid "Deleting instance files %s"
msgstr "Suppression des fichiers d'instance %s "

#: nova/virt/libvirt/driver.py:6150
#, python-format
msgid "Deletion of %s failed"
msgstr "La suppression de %s a échoué "

#: nova/virt/libvirt/driver.py:6154
#, python-format
msgid "Deletion of %s complete"
msgstr "Suppression de %s est complète"

#: nova/virt/libvirt/firewall.py:115
msgid "Called setup_basic_filtering in nwfilter"
msgstr "setup_basic_filtering appelé dans nwfilter"

#: nova/virt/libvirt/firewall.py:123
msgid "Ensuring static filters"
msgstr "Garantie des filtres statiques"

#: nova/virt/libvirt/host.py:569
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: %(ex)s"
msgstr ""
"Incapable d'utiliser les liste API de domaines par bloc, on revient au "
"chemin : %(ex)s"

#: nova/virt/libvirt/imagebackend.py:367
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""
"Echec à obtenir les informations d'image du chemin %(path)s; erreur : "
"%(error)s"

#: nova/virt/libvirt/imagecache.py:191
#, python-format
msgid "Writing stored info to %s"
msgstr "Ecriture d'informations stockées dans %s"

#: nova/virt/libvirt/imagecache.py:414
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash stored"
msgstr ""
"image %(id)s à (%(base_file)s) : vérification d'image ignorée, aucun hachage "
"stocké"

#: nova/virt/libvirt/imagecache.py:423
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr "%(id)s (%(base_file)s) : génération d'un total de contrôle"

#: nova/virt/libvirt/imagecache.py:452
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:455
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:505
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr "image %(id)s à (%(base_file)s) : vérification"

#: nova/virt/libvirt/imagecache.py:529
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""
"image %(id)s à (%(base_file)s) : en cours d'utilisation : sur ce noeud "
"%(local)d local, %(remote)d sur d'autres noeuds partageant ce stockage "
"d'instance"

#: nova/virt/libvirt/imagecache.py:612
#, python-format
msgid "Active base files: %s"
msgstr "Fichiers de base actifs : %s"

#: nova/virt/libvirt/imagecache.py:615
#, python-format
msgid "Corrupt base files: %s"
msgstr "Fichiers de base endommagés : %s"

#: nova/virt/libvirt/imagecache.py:619
#, python-format
msgid "Removable base files: %s"
msgstr "Fichiers de base pouvant être retirés : %s"

#: nova/virt/libvirt/utils.py:250
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:576
msgid "findmnt tool is not installed"
msgstr "L'outil findmnt n'est pas installé"

#: nova/virt/vmwareapi/driver.py:450
#, python-format
msgid "Invalid cluster or resource pool name : %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:434
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:351
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:354
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1264
msgid "Destroyed the VM"
msgstr "Machine virtuelle détruite"

#: nova/virt/vmwareapi/vmops.py:721
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1201 nova/virt/xenapi/vmops.py:1665
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""
"Arrêt détecté, %(instance_count)d redémarrée dans les %(timeout)d secondes"

#: nova/virt/vmwareapi/vmops.py:1205 nova/virt/xenapi/vmops.py:1669
msgid "Automatically hard rebooting"
msgstr "Réinitialisé automatiquement"

#: nova/virt/vmwareapi/volumeops.py:441
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate backing "
"disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection.  "
"Networking files will not bemanipulated"
msgstr ""
"Les outils XenServer installés dans cette image peuvent effectuer une "
"injection réseau. Les fichiers réseau ne seront pas manipulés"

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""
"Des outils XenServer sont présents dans cette image mais ils ne peuvent pas "
"effectuer une injection réseau "

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr "Les outils XenServer ne sont pas installés dans cette image"

#: nova/virt/xenapi/host.py:75
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database: "
"assuming it is a worker VM and skip ping migration to a new host"
msgstr ""
"L'instance %(name)s en cours d'exécution sur %(host)s est introuvable dans "
"la base de données : on suppose qu'il s'agit d'une machine virtuelle de "
"travailleur et le ping de migration pour un nouvel hôte est ignoré"

#: nova/virt/xenapi/vm_utils.py:393
#, python-format
msgid "VBD %s already detached"
msgstr "VBD %s déjà déconnecté"

#: nova/virt/xenapi/vm_utils.py:396
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt %(num_attempt)d/"
"%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:683
#, python-format
msgid "Deleted %s snapshots."
msgstr "Snapshots %s supprimés."

#: nova/virt/xenapi/vm_utils.py:1326
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""
"Données de création de l'image, capacité du cache : %(cache)s, téléchargé : "
"%(downloaded)s durée : %(duration).2f secondes pour l'image %(image_id)s"

#: nova/virt/xenapi/vm_utils.py:2174
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr "Déconnexion VDI périmé %s à partir de l'ordinateur domU"

#: nova/virt/xenapi/vm_utils.py:2467
msgid "Manipulating interface files directly"
msgstr "Manipulation directe des fichiers d'interfaces"

#: nova/virt/xenapi/vm_utils.py:2476
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""
"Echec du montage du système de fichiers (attendu pour les instances non "
"Linux) : %s"

#: nova/virt/xenapi/vmops.py:1259
msgid "Starting halted instance found during reboot"
msgstr "Démarrage de l'instance interrompue détectée durant le redémarrage"

#: nova/virt/xenapi/vmops.py:1463
msgid "Destroying VM"
msgstr "Destruction de la machine virtuelle"

#: nova/virt/xenapi/volumeops.py:64
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""
"Le point de montage %(mountpoint)s à été détaché de l'instance "
"%(instance_name)s"
